### PR TITLE
Pull Request For Design Tear Down Code Review

### PR DESCRIPTION
**Pull request by menyagah**
# In this section I did the following:
 - Created the header.
 - Added the logo.
- Added the search bar without the icon.
- Created the content section.
- Did a tear down of the avatar section
 - Added a mock-up of the footer.
- Made css validation fixes.
- Made html validation fixes.
- Made the changes required by the TSE
- Made additional changes requested by the TSE as follows:
   - Changed the layout colour.
   - Fixed the improper usage of the html article element.

### CODE REVIEW

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! my name is Mario, congratulation on your project! it look excellent! 👏  👏 

Although, aesthetically your project does not need any changes your code does.

## Changes required ❗️ 

- [x] There are errors on your HTML file, please remember to validate your HTML using this validator: https://validator.w3.org/#validate_by_upload 

- [x] There are a lot of repeated CSS rules on your file, please keep your code DRY (Don't repeat yourself). For example `justify-content: center` and `align-items: center;` are used over 20 times.  You can read this article if you need further guidelines.

- [x] Use more semantic HTML. You can use `article` instead of `div` several times. You can read about semantic tags in here: https://www.lifewire.com/why-use-semantic-html-3468271

Other than that your project it's really well done 🎖 🏅  , just a little bit to much focused on the "looks".

After making the mentioned changes please resubmit your project for another review.

Cheers!

## Code review by Mario Enrique Delgado Naranjo

**Comment by menyagah** [comment]
Hello Mario

Sorry for the late reply. Thank you for the review, I am working on it.

Thanks.

**Comment by uryelah** [comment]
### Code under review by Sarah Chamorro 👩‍🚀

**Comment by uryelah** [comment]
Hello **Martin Mugo**, I'm Sarah, your reviewer for this PR 👩‍🚀 

You did a good job completing most of the required changes from the last review, congrats! 

**Great job at:** 🥇 
- Fixing your HTML validation errors
- DRYing up your CSS rules
- Writing a great PR message
- doing an amazing job with fonts, positioning, and spacing (not everyone pays attention to the rotation, really good work there.)

----

**Now for the missing bit.**

### Required changes 🛠 

I see that you did an effort to make your HTML more semantic, and you are almost there.
The issue is that after the two top articles you are not using the `<article>` in it's optimal way.
Please read this post and pay special attention to the second code snippet: [article-tag](https://html5-tutorial.net/new-section-tags/article-tag/)

- [x] Use `<article>` for all content that makes sense in its own. Ex:. the divs .main_below-1 and .main_below-2 and the individual divs inside .articles.

- [x] Use `<section>` for the class .articles element. Check this [MDN guide on how to use section](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines). 

-------

**Optional changes**

### Visual weight

For the design teardown color is not needed, you should just use the greyscale to visualize the visual weight of the page components. When you use, even if just a little, color besides grey it calls a lot of attention to itself.

- [x]  [OPTIONAL] There are colored elements in your page: `rgb(245, 239, 239)`, `rgb(23, 85, 100)`, etc. Please make them shades of grey.

**Tip: ** If you need a quick and dirty grey you can just set all the rgb values or HEX equally.
Ex:. `rgb(245, 245, 245)`, `rgb(33,33,33)`, `#ccccccc`

-------

**Kindly fix the required changes above and request a new code review**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by menyagah** [comment]
Hello Sarah

Thanks a lot for the on time review. I am working on the pointed issues
right now.

**Comment by uryelah** [comment]
Hey Martin, thanks for the fixes.
**Great job!💯** 

You should still review the `<article>` and `<section>` tags a bit more, when you have the time, to make sure you implement them in your next projects.

But the changes you made are enough for now 🛩 

### Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------
    
 **Keep being an awesome dev and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by menyagah** [comment]
Hey Sarah

Sure thing will do. Thanks for the feedback!

**Pull request merged**
